from typing import List
import requests

def download_list(url: str) -> List[str]:
    response = requests.get(url)
    response.raise_for_status()  # Ensure we notice bad responses
    return response.text.splitlines()

def add_block_ip(raw_list: List[str]) -> List[str]:
    result = []
    for line in raw_list:
        result.append(
            "0.0.0.0 " + line.strip()
        )
    return result

def remove_comments(raw_list: List[str]) -> List[str]:
    result = []
    for line in raw_list:
        line = line.strip()
        if line and not line.startswith("#"):
            result.append(line)
    return result

def make_unique(raw_list: List[str]) -> List[str]:
    return list(set(raw_list))

def header(block_list_no: int) -> List[str]:
    header_text = f"""
#########################################################################
#                                                                       #
#            THIS FILE IS AUTOMATICALLY GENERATED BY GARLIC.            #
#                               _____                                   #
#                            .-'     '-.                                #
#                           /  |     |  \                               #
#                          /   |     |   \                              #
#                         |    |     |    |                             #
#                         |    |     |    |                             #
#                          \   |     |   /                              #
#                           \  |     |  /                               #
#                            '. |   | .'                                #
#                              '-._.-'                                  #
#                               (   )                                   #
#                                ( )                                    #
#                                                                       #
#########################################################################
# Information:
# BlockList No: {block_list_no}

"""

    return header_text.split("\n")